### ISSUE TITLE
Update documentation to reflect configuration changes

### ISSUE THREAD

**Issue by exabyssus** [nuxt-community/sanity-module#115]
### Version
module: 0.9.0

### Nuxt configuration
```
{
  buildModules: ['@nuxtjs/sanity']
}
```

## Reproduction
Running `yarn build` with configuration currently on "Quick start" page.
[](https://sanity.nuxtjs.org/quick-start)
Fatal Error is produced.
```
✖ Nuxt Fatal Error: TypeError: Module should export a function: @nuxtjs/sanity 
```

## Additional information
Since version `0.8.0` configuration should look like this 
```
{
  buildModules: ['@nuxtjs/sanity/module']
}
```

**Comment by danielroe** [comment]
Thanks! Good spot.
