### ISSUE TITLE
How to integrate with @sanity/image-url?

### ISSUE THREAD

**Issue by mornir** [nuxt-community/sanity-module#19]
Hey!
I was hoping I could use the `createClient` to configure the client for the @sanity/image-url package, but it doesn't work 🤔
What the best/cleanest of using `@sanity/image-url` with the Nuxt sanity-module?

```js
// Nuxt plugin
import imageUrlBuilder from '@sanity/image-url'
import { createClient } from '@nuxtjs/sanity'

const configSanity = {
  projectId: 'tufjlt9c',
  dataset: 'production',
}

const client = createClient(configSanity)
const builder = imageUrlBuilder(client)

function urlFor(source) {
  return builder.image(source)
}

export default (context, inject) => {
  inject('urlFor', urlFor)
}
```
```html
<img :src="$urlFor(movie.poster)" :alt="movie.title + ' poster'" />
```

![image](https://user-images.githubusercontent.com/1411843/95658541-78953900-0b1b-11eb-889a-855e6a9df5a0.png)

**Comment by danielroe** [comment]
Try this:
```js
// Nuxt plugin
import imageUrlBuilder from '@sanity/image-url'

const configSanity = {
  projectId: 'tufjlt9c',
  dataset: 'production',
}

export default ({ $sanity }, inject) => {
  const builder = imageUrlBuilder($sanity.client)

  function urlFor(source) {
    return builder.image(source)
  }

  inject('urlFor', urlFor)
}
```

**Comment by mornir** [comment]
thanks for the quick response 😃
but still no luck: https://github.com/mornir/movies-web/blob/master/plugins/image-builder.js
When logging, I can see that the client was initialized.

(I'd like to use the crop & hotspot feature of the studio, which I assume SanityImage can't render)

**Comment by mornir** [comment]
I'm using the minimal client (piconsanity). I tried using `@sanity/client`, but I get the following error, although I have it installed:
![image](https://user-images.githubusercontent.com/1411843/95659846-345a6680-0b24-11eb-8272-cb181bfdc380.png)

**Comment by danielroe** [comment]
@mornir That's a bug - give me a sec.

**Comment by danielroe** [comment]
@mornir Try with `v0.3.7` - should correctly detect `@sanity/client`

**Comment by mornir** [comment]
Nice! The warning is gone, but now I get this error:
```bash
 ERROR   /

server.js:612
      useOfficialClient = !!(/*require.resolve*/)(33);        
                                                ^

SyntaxError: Unexpected token ')'
    at new Script (vm.js:88:7)
    at C:\projects\movies-web\node_modules\vue-server-renderer\build.prod.js:1:77446
    at o (C:\projects\movies-web\node_modules\vue-server-renderer\build.prod.js:1:77509)
    at C:\projects\movies-web\node_modules\vue-server-renderer\build.prod.js:1:78172
    at new Promise (<anonymous>)
    at C:\projects\movies-web\node_modules\vue-server-renderer\build.prod.js:1:78080
    at Object.renderToString (C:\projects\movies-web\node_modules\vue-server-renderer\build.prod.js:1:81615)
    at SSRRenderer.render (C:\projects\movies-web\node_modules\@nuxt\vue-renderer\dist\vue-renderer.js:3822:38)
```

**Comment by mornir** [comment]
The error occurs when setting the client to minimal.

**Comment by danielroe** [comment]
Apologies for that. Let's try `v0.3.8`.

**Comment by mornir** [comment]
@danielroe Thanks for the quick fix!
`!!((process.client || process.server) ? require.resolveWeak('@sanity/client') : require('@sanity/client'))`😵😄

Back to my original question:
Initializing the image builder with `context.$sanity` works when using `minimal: false`, but not with `minimal: true`, which is odd, because this does work:
```js
import sanity from 'picosanity'
import imageUrlBuilder from '@sanity/image-url'

const client = sanity({
  projectId: 'tufjlt9c',
  dataset: 'production',
})

const builder = imageUrlBuilder(client)
const urlFor = (source) => builder.image(source).auto('format')

export default (context, inject) => {
  inject('urlFor', urlFor)
}
```

**Comment by danielroe** [comment]
@mornir I'll need to look into the image URL builder. I think I recall it is only requesting the client to get the configuration, which it's assuming is available - as it doesn't need to perform any fetches.

**Comment by danielroe** [comment]
Answer is don't pass in the current, just the config, which image builder supports as well. Or we can modify the minimal client to return its config via the `clientConfig`

**Comment by mornir** [comment]
Oh I see 😯
yeah, the following plugin would be neat. Are there any downsides in exposing the client config like this?
```js
import imageUrlBuilder from '@sanity/image-url'
export default ({ $sanity }, inject) => {
  const builder = imageUrlBuilder($sanity) // image-url will automatically look for the clientConfig key, right?
  function urlFor(source) {
    return builder.image(source)
  }
  inject('urlFor', urlFor)
}
```

Now I'm importing the Sanity config from the Nuxt config:
```js
import imageUrlBuilder from '@sanity/image-url'
import config from '../nuxt.config.js'

export default (context, inject) => {
  const builder = imageUrlBuilder(config.sanity)
  function urlFor(source) {
    return builder.image(source)
  }
  inject('urlFor', urlFor)
}
```
I had to explicitly set `dataset` to `production` for it to work (although it's the default value).

Now that I think about it, the best would be that the `nuxt-sanity` plugin provides the urlFor image helper globally.

**Comment by danielroe** [comment]
I propose exposing the config like so:
```js
import imageUrlBuilder from '@sanity/image-url'
export default ({ $sanity }, inject) => {
  const builder = imageUrlBuilder($sanity.config)

  function urlFor(source) {
    return builder.image(source)
  }

  inject('urlFor', urlFor)
}
````

I'm reluctant to embed `@sanity/image-url` as it will increase the bundle size by 7Kb (parsed JS) when not everyone will use it.

**Comment by mornir** [comment]
Good for me 👍

**Comment by danielroe** [comment]
... now usable in `v0.3.9`

**Comment by mornir** [comment]
Thanks!
