### ISSUE TITLE
Not found npm module

### ISSUE THREAD

**Issue by liqueflies** [nuxt-community/sanity-module#193]
Hello, I am trying to update to 0.9.4 but there is no npm page anymore for the package:

https://www.npmjs.com/package/@nuxtjs/sanity

What's happened?

Thank you in advice! :)

**Comment by danielroe** [comment]
@liqueflies I strongly suspect it's a temporary npm issue as I can visit the page.

**Comment by liqueflies** [comment]
Now it's showing also to me.
I wasn't able also to install (403 forbidden error)

Now it's perfect, sorry for dumb reporting.

Thank you :)
