### ISSUE TITLE
How to generate sanity image url?

### ISSUE THREAD

**Issue by AxelBriche** [nuxt-community/sanity-module#20]
Hello, how can I generate a sanity image url inside my template?
I use Snipcart and for each snipcart button, I want provide the a product image.

The <SanityImage /> component is ok for display an image, but how can I only generate the url?
Thanks.

Note: My sanity config is inside my nuxt.config.js file.

**Comment by mornir** [comment]
Hi!
@danielroe recently added a nice feature: [renderless component for images](https://sanity.nuxtjs.org/helpers/images#example-2)
If the renderless component doesn't cover your use case, you need to use the [@sanity/image-url](https://github.com/sanity-io/image-url) package.

**Comment by liqueflies** [comment]
Hello @AxelBriche,
I've managed like that:

`~/plugins/urlResolver.js`

```
import imageUrlBuilder from '@sanity/image-url'

export default ({ $sanity }, inject) => {
  const builder = imageUrlBuilder($sanity.config)

  function urlFor(source) {
    return builder.image(source)
  }

  inject('urlFor', urlFor)
}
```

imported into `nuxt.config.js`

```
  plugins: [
   ...,
    '~/plugins/urlResolver',
   ...
  ]
```

and then into my vue instance:

```
<img :src="$urlFor(image.asset._ref).url()" />
```

or you can call on your computed, methods, or so...

```
mounted() {
   console.log(this.$urlFor(this.image.asset._ref).url())
}
```

hope can be this helpful.

L.

**Comment by mornir** [comment]
Yes, this is also what I do. 👍

I recommend adding `format('auto')` inside the plugin to automatically get webp images in supported browsers:
`builder.image(source).auto('format')`

When using the plugin, I think it's not necessary to pass asset._ref. This should also work:
`<img :src="$urlFor(image).url()" />`
