### ISSUE TITLE
Nested lists are not rendered correctly

### ISSUE THREAD

**Issue by estallio** [nuxt-community/sanity-module#266]
#### 1. When defining multiple lists with different list-styles without an empty line between, the plugin produces one merged list, that includes all the elements.

Screenshot of Sanity Studio:
<img width="204" alt="Bildschirmfoto 2021-10-11 um 09 54 52" src="https://user-images.githubusercontent.com/26573555/136824091-bfeafac5-f12a-4bd6-8881-30d676bf8e42.png">

Screenshot of website (rendered Content):
<img width="116" alt="Bildschirmfoto 2021-10-11 um 10 08 14" src="https://user-images.githubusercontent.com/26573555/136824099-4b17f2b0-0fb1-4a26-8e91-a83a39ae65e8.png">

When adding an empty line, it works (screenshot of Sanity Studio):
<img width="226" alt="Bildschirmfoto 2021-10-11 um 09 54 40" src="https://user-images.githubusercontent.com/26573555/136824086-07b11f18-e86c-49bd-aba4-80cfefd055dc.png">

With the empty line, it is rendered correctly (screenshot of website):
<img width="134" alt="Bildschirmfoto 2021-10-11 um 10 07 08" src="https://user-images.githubusercontent.com/26573555/136824095-47cf9f8b-0f19-4a81-b57d-f6200e132968.png">

This is caused by the [`walkList`](https://github.com/nuxt-community/sanity-module/blob/c7c35aff5ba89437dfeefa9ee25d48c326450861/src/components/sanity-content.ts#L201) method in [`sanity-content.ts`](https://github.com/nuxt-community/sanity-module/blob/c7c35aff5ba89437dfeefa9ee25d48c326450861/src/components/sanity-content.ts). The check if the last block was already an list does only check the levels, but not the `listItem` property from sanity, which we get like this (screenshot of Vision extension of Santiy Studio):
<img width="329" alt="Bildschirmfoto 2021-10-11 um 09 56 07" src="https://user-images.githubusercontent.com/26573555/136824092-431afeea-73ae-4716-ac87-aed4c6519cf7.png">

#### 2. Multi level lists are not working correctly. Things like the following are not rendered correctly:
<img width="248" alt="Bildschirmfoto 2021-10-11 um 10 41 39" src="https://user-images.githubusercontent.com/26573555/136824101-fb71a3a9-1504-491d-a0c0-ab5939539540.png">
<img width="154" alt="Bildschirmfoto 2021-10-11 um 10 41 57" src="https://user-images.githubusercontent.com/26573555/136824102-74b3d473-d803-4fda-9219-79f4a9e3f2be.png">

Special care should be taken to produced wellformed HTML code:
- [How to write W3C compliant multi-level bullet points in HTML?](https://stackoverflow.com/questions/4465562/how-to-write-w3c-compliant-multi-level-bullet-points-in-html)
- [Proper way to make HTML nested list?](https://stackoverflow.com/questions/5899337/proper-way-to-make-html-nested-list)
- [Add style to multi-level UL : ul « Tags « HTML / CSS](http://www.java2s.com/Code/HTMLCSS/Tags/AddstyletomultilevelUL.htm)

Additionally, it should be taken care of the list implementation in Sanity Studio so that the editor and the rendered HTML show at least similar behaviour - expect a view bugs in the Studio like [https://github.com/sanity-io/sanity/issues/1338](https://github.com/sanity-io/sanity/issues/1338).

### Version
module: 0.10.0 
nuxt: 2.15.8 

### Nuxt configuration
 - [x] universal
 - [x] spa

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by danielroe** [comment]
Thank you for this! Apologies for the time it took me to resolve.
