### ISSUE TITLE
Update @nuxt/kit in order to work with nuxt/bridge

### ISSUE THREAD

**Issue by liqueflies** [nuxt-community/sanity-module#277]
### Is your feature request related to a problem? Please describe.
If I use this module with @nuxt/bridge it throws an error:

` TypeError: nuxtCtx.set is not a function`

### Describe the solution you'd like to see
No error on dev command

### Describe alternatives you've considered
-

### Additional context
I runned yarn why @nuxt/kit and noticed this message:

```
=> Found "@nuxtjs/sanity#@nuxt/kit@0.6.4"
info This module exists because "@nuxtjs#sanity" depends on it.
```

refer to https://github.com/nuxt/framework/issues/779

Thank you!

**Comment by liqueflies** [comment]
Hi @danielroe,
is this so expansive to achieve or it is just a package update?
Can I do something to help?

Thank you 💚

**Comment by danielroe** [comment]
v1 of `@nuxtjs/sanity` has been released with support for Nuxt 3 and Nuxt Bridge. Let me know how it goes, and feel free to raise any issues! ❤️
