### ISSUE TITLE
setting up Sanity with Nuxt 3

### ISSUE THREAD

**Issue by MartCube** [nuxt-community/sanity-module#296]
Hello there, this is a great plugin and a lot of respect for that.
I have a short question where I'm exploring the new Nuxt 3 beta.
Is it possible to use this plugin in Nuxt 3 now ?
Has anyone have some example to share ?

**Comment by danielroe** [comment]
v1 of `@nuxtjs/sanity` has been released with support for Nuxt 3 and Nuxt Bridge. Let me know how it goes, and feel free to raise any issues! ❤️

**Comment by danielroe** [comment]
@OrhanOzkercin Please create a new issue with a reproduction and I'll take a look 👍
