### ISSUE TITLE
Support for using the configured Sanity client in `nuxt.config.js`

### ISSUE THREAD

**Issue by mornir** [nuxt-community/sanity-module#3]
When [generating dynamic routes](https://nuxtjs.org/guides/configuration-glossary/configuration-generate#function-which-returns-a-promise), I need the Sanity client to fetch all routes. Is there a way I can access the configured client in nuxt.config.js? Or do I need to import it and configure it again?

**Comment by danielroe** [comment]
This is an interesting idea. Would importing a `createClient` helper that returns an auto configured client (based on the settings in`nuxt.config`) suit your use-case?

**Comment by mornir** [comment]
Yes, that would perfect for my use case 👍

**Comment by mornir** [comment]
I had a look at the code. Actually there's already a helper function exported. So I can do this:

```js
import { createClient } from '@nuxtjs/sanity'
export const configSanity = {
  projectId: 'xxxxxxx',
  withCredentials: true,
  useCdn: false,
  minimal: true,
}
const client = createClient(configSanity)
export default { 
 // nuxt config....
   sanity: {
      ...configSanity,
    },
}
```
I see that only the main nuxtModule function has access to the moduleOptions. So I guess it's not that easy to export an auto-configured client? If I want to add this enhancement, where should I start in the code?

**Comment by arlenpeiffer** [comment]
+1 to this idea

**Comment by danielroe** [comment]
The `createClient` function will create a minimal client. The challenge is that a lot of the configuration of the client comes from the `nuxt.config` file and so using it *within* the file runs the risk of circular dependency. If you're happy to redefine the configuration it should be possible to do:

```js
// for minimal client
import { createClient } from '@nuxtjs/sanity'
// for official Sanity client
import createClient from '@sanity/client'

const client = createClient({
  projectId: 'xxxxxxx',
  withCredentials: true,
  useCdn: false,
})

// ... use client
```

Do you think this is straightforward enough? It doesn't feel that inconvenient to me, but I'm open to being persuaded otherwise.

**Comment by mornir** [comment]
Yes, this is what I'm doing and it's perfectly fine 😉 I'll submit a pull request to document it.
