### ISSUE TITLE
[DX Enhancement] Suppress missing dep warning from Webpack

### ISSUE THREAD

**Issue by mornir** [nuxt-community/sanity-module#33]
### Version
module: 0.3.9
nuxt: 2.14.6

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [ ] universal
 - [x] spa

### Nuxt configuration
https://github.com/mornir/terminofeu-web/blob/dev/nuxt.config.js

## Reproduction
https://github.com/mornir/terminofeu-web

**Link:** 
- [x] GitHub repository

#### What is expected?
The following warning is not shown when client is set to minimal: `Warning: Module not found: Error: Can't resolve '@sanity/client'`

#### What is actually happening?
Warning is shown regardless of minimal setting

## Additional information
If the minimal key is missing, the warning is correct: " To disable this warning, set sanity: { minimal: true } in your nuxt.config.js."

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by danielroe** [comment]
@mornir Thanks for this! This warning is generated by webpack because `require('@sanity/client')` is present in the module code, even though it isn't being run. It's not a bug, just an annoyance.

However, I'll see what I can do.

**Comment by mornir** [comment]
Yes, it's just a bit annoying with HMR. The warning is printed at every saves.

**Comment by mornir** [comment]
I had a (amateur) look into it. Actually the following line just checks if the dependency "@sanity/client" is installed, returning a boolean?
`!!(process.client || process.server ? require.resolveWeak("@sanity/client") : require("@sanity/client"));`
What puzzles me is that this block of code is not even executed when minimal is set to true and the error is not caught by the try/catch blocks. Like you said, this is just Webpack trying to be helpful by showing that warning. (Curious to see if Webpack 5 throws the same warning.)

I had a quick look online and I didn't find anything conclusive to suppress that warning.

If I do install the `@sanity/client` dependency and set `minimal` to `true`, I'm guessing that `@sanity/client` won't be included in the production bundle? I can live with that solution.

Another solution would be to just remove that check. Then instead of a nice consola warning, the console would print:
`This dependency was not found: @sanity/client.` If this solution is chosen, I would change the default value of `minimal` to `true`.
