### ISSUE TITLE
Can not install Sanity with Nuxt3

### ISSUE THREAD

**Issue by OrhanOzkercin** [nuxt-community/sanity-module#331]
I am very new to Sanity and Nuxt. I tried to set it up but get problems shown below. 
I followed https://sanity.nuxtjs.org/getting-started/quick-start

![image](https://user-images.githubusercontent.com/25130814/155840864-33762066-9236-462c-9792-fca646ee2a7a.png)

![image](https://user-images.githubusercontent.com/25130814/155840869-b08e56a3-ae34-4813-a989-5c5eecbe38a8.png)

![image](https://user-images.githubusercontent.com/25130814/155840872-d857577a-12d0-43a3-9b3b-d874dbe521aa.png)

Here are my deps.

```js
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.10.0",
    "@typescript-eslint/parser": "^5.10.0",
    "autoprefixer": "^10.4.2",
    "eslint": "^8.7.0",
    "nuxt3": "latest",
    "postcss": "^8.4.5",
    "prettier": "^2.5.1",
    "prettier-plugin-tailwindcss": "^0.1.4"
  },
  "dependencies": {
    "@nuxtjs/composition-api": "^0.31.0",
    "@nuxtjs/sanity": "^1.1.1",
    "@nuxtjs/tailwindcss": "5.0.0-2",
    "@pinia/nuxt": "^0.1.8",
    "eslint-plugin-nuxt": "^3.1.0",
    "pinia": "^2.0.9",
    "sass": "^1.49.0"
  }
```

**Comment by danielroe** [comment]
What are your nuxt.config.ts and tsconfig.json? Are you just worried about the IDE warning, or do you get an error when you run Nuxt?

How did you create your Nuxt project? I see you have some dependencies that aren't for Nuxt 3, like the Nuxt composition API module.

**Comment by OrhanOzkercin** [comment]
I am not completely sure. I installed Nuxt with following their docs. This is the first time I am using.

tsconfig.json
```js
{
  // https://v3.nuxtjs.org/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "types": ["@pinia/nuxt"]
  }
}
```

nuxt.config.ts

```js
import { defineNuxtConfig } from "nuxt3";

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  buildModules: ["@pinia/nuxt"],
  modules: ["@nuxtjs/sanity"],
  sanity: {
    projected: "{{projectId}}",
  },
  build: {
    postcss: {
      postcssOptions: require("./postcss.config.js"),
    },
  },
  css: ["~/assets/css/tailwind.scss", "~/assets/css/global.scss"],
});

```

When I try to run code below I throws an error like shown below

```js

const sanity = useSanity();

console.log(sanity);
```

![image](https://user-images.githubusercontent.com/25130814/155844192-a92061c2-835b-4d2f-9c35-0e6be5574a90.png)


I may try to clean install and try it again.

**Comment by danielroe** [comment]
Here's a working example: https://stackblitz.com/edit/github-dz5ugi.

It's not the cause of your problem, but there's no need to add `@pinia/nuxt` to your types.

**Comment by OrhanOzkercin** [comment]
Yeah, I saw it. There should be a problem about my configs. Thanks a lot.

**Comment by danielroe** [comment]
Don't hesitate to get back in touch if there's any way I can help.

(You may just need to upgrade nuxt - run `npx nuxi upgrade`...)

**Comment by OrhanOzkercin** [comment]
> Don't hesitate to get back in touch if there's any way I can help.
> 
> (You may just need to upgrade nuxt - run `npx nuxi upgrade`...)

 I have created a new project and tried it. It worked. But TS error is still there FYI. Thank you very much for help.

Here is TS error I mentioned.
![image](https://user-images.githubusercontent.com/25130814/155844975-5245c9d0-0f0c-47c4-85e4-35eb34bb1db7.png)
