### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by macloganvincit** [nuxt-community/sanity-module#344]
I'm trying to run this package on a project and have been running into this error: 
  ✖ Nuxt Fatal Error                                                                                       │
                                                                                                               │
     Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './module' is not defined by "exports" in         
      .../node_modules/@nuxtjs/sanity/package.json  

I have tried many different versions of node, npm and nuxt with no success. I am unable to use Nuxt 3 as it is for a project that requires stability.

Here are my dependencies in package.json:
![image](https://user-images.githubusercontent.com/93001615/157558748-e13da546-b58b-4842-85e0-0da8645717c3.png)

and how I have it configured in nuxt.config.js:
![image](https://user-images.githubusercontent.com/93001615/157558701-593db65f-79e4-4433-916b-df3668cf8910.png)

Does anyone have a solution to this? It's driving me crazy.

**Comment by danielroe** [comment]
Yes. You need to install the previous version of `@nuxtjs/sanity`: `^0.1.1`. Docs for this version are available at https://v0.sanity.nuxtjs.org/.

**Comment by macloganvincit** [comment]
I had done my install per the setup instructions per that doc and I was trying to find any mention of versioning and couldn't find that. 

Thanks for the answer. That fixed it!
