### ISSUE TITLE
Missing Type Definitions

### ISSUE THREAD

**Issue by patrickdaley** [nuxt-community/sanity-module#39]
Property $sanity does not exist on type 'Context'. 

tsconfig.json compilerOptions:

```
"types": [
      "@types/node",
      "@nuxt/types",
      "@nuxtjs/sanity"
    ]
```

**Comment by danielroe** [comment]
@patrickdaley Could you give me an example of how you're trying to use it?

**Comment by patrickdaley** [comment]
Yup: `async fetch({ route, $sanity }) { ... }`

**Comment by danielroe** [comment]
@patrickdaley you would use it like: `async fetch({ app: { $sanity }}) { ... }`

**Comment by patrickdaley** [comment]
Ah, of course, thank you!
