### ISSUE TITLE
My sanity.json is not working at all 😔

### ISSUE THREAD

**Issue by rylanharper** [nuxt-community/sanity-module#392]
Hey there! Thank you for working on/maintaining this plugin. I am using it with Nuxt3 for a client project and everything is going well except for the fact that it doesn't seem to pick up my `sanity.json` file in my root directory... Instead I have to enter my sanity dataset in my `nuxt.config.js`:
```
sanity: {
  projectId: 'my-project-id',
  dataset: 'production'
}
```
This ends up working fine, but if I remove this and add in a `sanity.json` file I get the following error if I try and query anything such as `title` or image, etc.: `Cannot read properties of undefined (reading 'title')`. I am not sure whats going on 🤔

### Version
module: `"@nuxtjs/sanity": "^1.2.0"`
nuxt: `"nuxt": "3.0.0-rc.1"`

### What is expected?
My `sanity.json` dataset/projectId should be picked up by the plugin and the data should fetch without any errors

### What is actually happening?
The `sanity.json` doesn't seem to be having any effect in my project. It could possibly be due to my directory structure, but it seems unlikely (my `sanity.json` lives within my `/web` folder:
```
/studio
/web
```
```
{
  "api": {
    "projectId": "sample-project-id",
    "dataset": "production"
  }
}
```

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by rylanharper** [comment]
Hey @danielroe! Thanks for getting back to me, this issue still persists. I have successfully launched a static site I am working on for a client (although a WIP) and all the data is queried properly (so no dev-tools errors on live and routes all work). I still cant seem get my `sanity.json` to work though, but when I add my dataset into the `nuxt.config.js` everything works just fine. 

Yep, I will get you the a repo! Please give me the weekend and I will get you a repo hopefully by Monday or Tuesday. I am just swamped with work this week 😓
