### ISSUE TITLE
Having trouble querying global data within app.vue

### ISSUE THREAD

**Issue by rylanharper** [nuxt-community/sanity-module#405]
Hey there! I am having trouble querying my seo data globally using the `useHead` composable within my core `app.vue`. I have the following groq query for my `seoSettings`, but the meta content comes back as `undefined`. I have double checked my data and there are no type-errors and I can query the data just fine within my `<template` such as `{{ seo.metaTitle }}`, etc. Perhaps just have my script setup wrong or is there a better way of querying global data through the app? Any advice will help:)

`app.vue`:
```
<template>
  <!-- Nuxt page-->
  <main role="main" id="main">
    <nuxt-page />
	// this works
    {{ seo.metaDesc }}
  </main>
</template>

<script setup lang="ts">
const query = groq`*[_type == "seoSettings"] {
  metaTitle,
  metaDesc
}`

const { data: seo } = await useSanityQuery(query, {})

useHead({
  meta: [
	// this does not work
    { property: 'title', content: seo.metaTitle }
  ]
})
</script>
```

**Comment by rylanharper** [comment]
@danielroe Hmm it still comes back as `undefined`... However referencing the value's index works: 
`seo.value[0].metaTitle` 🎉

Here is a working reference for global useHead:
```
<script setup lang="ts">
const query = groq`*[_type == "seoSettings"] {
  metaTitle,
  metaDesc,
  metaKeywords
}`

const { data: seo } = await useSanityQuery(query, {})
console.log(seo.value[0])

useHead({
  meta: [
    // This works!
    { property: 'title', content: seo.value[0].metaTitle },
    { property: 'description', content: seo.value[0].metaDesc },
    { property: 'keywords', content: seo.value[0].metaKeywords.join(', ') }
  ]
})
</script>
```

Perhaps something like this can be added to the module docs since global data is very common when using Sanity.. Its not really a priority but it could really help:)

**Comment by danielroe** [comment]
I think you just need to tweak the query:

```js
- const query = groq`*[_type == "seoSettings"] {
+ const query = groq`*[_type == "seoSettings"][0] {
    metaTitle,
    metaDesc,
    metaKeywords
  }`
```

**Comment by rylanharper** [comment]
Yep you are absolutely correct! I forgot that `0` In my query..
