### ISSUE TITLE
Support for caching query results with SSG site

### ISSUE THREAD

**Issue by mrdannyjohnson** [nuxt-community/sanity-module#411]
This module is working great for me with Nuxt 3, thank you. 

However, I've recently tried to convert a site to SSG using [nuxi generate](https://v3.nuxtjs.org/api/commands/generate#nuxi-generate). I can see all the routes are created in .output/public and the content is in place. However, when I load a page, the sanity query is still being run on the client side.

I've tried a few combinations for _ssr_: and _target_: with no success. 

Is this module ready for to be used with nuxi generate?

Thank again

**Comment by mrdannyjohnson** [comment]
Ah, I hadn't fully appreciated the difference between full static and Nuxt3 SSG so thanks for the clarification @danielroe. 

If Sanity responses were cached on nuxt generate, does that create close to the 'full static' approach? Personally, I think I'd almost always use globally cached sanity queries if that were the case and the option available. 

I'll look at Nuxt Content to see if I can get a more thorough understanding 👍

**Comment by danielroe** [comment]
Yes, it would be very close to full static.

But it would need to be experimental so we could deprecate it if/when we have framework support for full static.

**Comment by mrdannyjohnson** [comment]
Thanks Rylan. On Vercel, there were client side requests to Sanity on navigation between routes. 

However, full static is now working perfectly using https://github.com/danielroe/nuxt-full-static and Nuxt v3.0.0-rc.7
