### ISSUE TITLE
SanityContent and SanityImage are not auto-imported

### ISSUE THREAD

**Issue by mornir** [nuxt-community/sanity-module#51]
Hi!
I've just updated to v0.4.0 and the helpers are no longer globally imported even though that I set `components: true`. Do I need to write more config for it to work?

Reproduction: https://github.com/mornir/movies-web

**Comment by mornir** [comment]
I see them during development in my .nuxt folder:
![image](https://user-images.githubusercontent.com/1411843/99297328-6740fa00-2848-11eb-8638-126ba081c211.png)

**Comment by mornir** [comment]
And I get this warning:
![image](https://user-images.githubusercontent.com/1411843/99297407-8475c880-2848-11eb-9fb4-243c584bad24.png)

**Comment by dylanmcgowan** [comment]
SanityContent + SanityImage are not auto imported in v0.6.0 with the components set to true, this should be re opened..

**Comment by danielroe** [comment]
@dylanmcgowan apologies! would you check that this issue is solved for you in 0.6.1?

**Comment by dylanmcgowan** [comment]
@danielroe thanks for the prompt fix, no more nuxt error!
