### ISSUE TITLE
Handling newline characters (\n)

### ISSUE THREAD

**Issue by mornir** [nuxt-community/sanity-module#61]
### Is your feature request related to a problem? Please describe.
When using hard break (shift+enter) in portable text, a newline `\n` character is added.
Those newlines characters are kept in the HTML, but are ignored when rendered by the `SanityContent` component. 

This is actually the default behavior of HTML/CSS. Adding `white-space: pre-line` solves the issue.
However I think that hardbreaks should by default render a new line, because this is how it looks in portable editors. I'm curious to hear opinions about this.

### Describe the solution you'd like to see
The `block-content-to-hyperscript` library [converts newline characters into `<br />`](https://github.com/sanity-io/block-content-to-hyperscript/blob/master/src/serializers.js#L102). It also let the the developer decide how to handle newline characters by passing their own function. Or to pass `false`, to keep newline characters, which is the current behavior of `SanityContent`.

### Describe alternatives you've considered
Let the developers add `white-space: pre-line` when using `SanityContent`. Maybe this is the cleanest solution?

---
I'm working on a pull request, taking the hyperscript library as a model, but I have a hard time to figure out how to implement that logic, starting with where that logic should reside in `sanity-content.ts`. Looking at the code of the hyperscript library, I'm also confusing at that statement `span === '\n'`. (Are all newlines divided into spans of text beforehand?🤔)

And I have a question about development of this module:
When running `yarn dev` and making changes to `sanity-content.ts`, changes are not reflected. Instead I need to stop the developing server, run `yarn build` and then restart the server with `yarn dev`. If I make changes directly to `dist/sanity-content.js`, changes are reflected upon saving. Is this the normal development workflow?
I can see some alias in nuxt.config.js that point to the TS files in src.

**Comment by danielroe** [comment]
@mornir So having taken a look at this, I'm not sure there is an easy fix within `SanityContent` as it would require turning text into HTML, which I think is somewhat against the grain of the Portable Text concept. I think the best solution is `white-space: pre-line` as you've suggested.

**Sample paragraph with newlines**:

```js
const children = [
  {
    "_key": "82dc1243fc1c",
    "_type": "span",
    "marks": [],
    "text": "d\n\n\nd"
  }
]
```

**Comment by mornir** [comment]
Thanks for looking into it!
Yes, I came to the same conclusion. When trying to add my code to SanityContent, the approach didn't feel right.

At first I thought that SanityContent stripped the newline characters, but actually they're still in the HTML. Using `white-space: pre-line` is easy and works as expected.

**Comment by silvio-e** [comment]
I am using this module for the first time and was confused about the new line handling. Thank god I found this issue here 😅 

> I'm not sure there is an easy fix within SanityContent, as it would require turning text into HTML

So far, I have used https://github.com/rdunk/sanity-blocks-vue-component, which produces a `<br>`, and this is actually what I also expect when portable text gets transformed into HTML. Because of that, the CSS workaround doesn't feel quite right to me.

@danielroe would you consider to add `<br>` for new lines?

**Comment by danielroe** [comment]
Yes, I would 👍

**Comment by joelisfar** [comment]
@danielroe is this still on the radar? Perhaps I'm doing something wrong but `\n`s don't seem to be spitting out `<br />`s by default.
