### ISSUE TITLE
"SyntaxError: Invalid regular expression: invalid group specifier name" on Safari

### ISSUE THREAD

**Issue by abdulrauf11** [nuxt-community/sanity-module#66]
### Version
module: 0.6.2
nuxt: 2.14.12

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration

```
export default {
  // Target: https://go.nuxtjs.dev/config-target
  target: 'static',

  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    title: 'sanity-test',
    htmlAttrs: {
      lang: 'en',
    },
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }],
  },

  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [],

  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [],

  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,

  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
    // https://go.nuxtjs.dev/eslint
    '@nuxtjs/eslint-module',
    '@nuxtjs/sanity',
  ],

  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [],

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {},

  // Sanity Configuration:
  sanity: {
    projectId: 'vgw104pb',
  },
}

```

## Reproduction
**Links:** 
- https://sad-heyrovsky-54a894.netlify.app/
- https://github.com/abdulrauf11/sanity-test

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

### Steps to reproduce
1. Open the site link: https://sad-heyrovsky-54a894.netlify.app/ on Safari.
2. View the console to see this error: `SyntaxError: Invalid regular expression: invalid group specifier name`

You can also test the GitHub repo locally.

Not sure if this is relevant but you can look at the sanity studio repo here: https://github.com/abdulrauf11/sanity-kitchen-sink/tree/main/studio

### What is actually happening?

<img width="842" alt="Screenshot 2021-01-31 at 2 28 32 AM" src="https://user-images.githubusercontent.com/26784406/106369098-81cb3f80-6370-11eb-973a-4e80785f5302.png">

**Comment by abdulrauf11** [comment]
The issue does not per

> I think it likely this might be the same issue as [nuxt/nuxt.js#8027](https://github.com/nuxt/nuxt.js/issues/8027).
> 
> Would you test without `@nuxtjs/sanity` and see if the issue persists?

The issue does not persist once I remove @nuxtjs/sanity

**Comment by abdulrauf11** [comment]
@danielroe I commented `@nuxtjs/sanity` and the issue went away.

- Github repo: https://github.com/abdulrauf11/sanity-test/tree/without-sanity
- Live link: https://6015eb460f0d0b0008fc3b23--sad-heyrovsky-54a894.netlify.app/

Please check the live link on Safari.

**Comment by abdulrauf11** [comment]
@danielroe Thanks a lot! 🙏

**Comment by danielroe** [comment]
Thanks for spotting this. A server dependency with an unsupported RegExp (`upath`) was being included in the client build - should be fixed in `v0.7.0`. Let me know if not :smiley:

**Comment by matthewlukedesign** [comment]
@danielroe - I was having the same issue and upgrading to 0.7.0 fixed it :)

**Comment by abdulrauf11** [comment]
@danielroe Brilliant, thanks! It's working now 😁

**Comment by fejiroofficial** [comment]
I have been on this blocker over the weekend. Upgrading to 0.7.0 worked for me.
