### ISSUE TITLE
fetch is not defined: using minimal client inside nuxt.config.js

### ISSUE THREAD

**Issue by mornir** [nuxt-community/sanity-module#67]
Hey! It's me again 😁

I'm using the minimal client inside `nuxt.config.js` in order to fetch all the routes at build time. I followed the approach you described here: https://github.com/nuxt-community/sanity-module/issues/3

```js
// for minimal client
import { createClient } from '@nuxtjs/sanity'

const client = createClient({
  projectId: 'xxxxxxx',
  useCdn: false,
})
```

But when calling `client.fetch`, I get the error `fetch is not defined`. At first, I thought it was the property `fetch` on the client object that was undefined, but it's actually the Fetch API that isn't defined.

I know that, in this case, the runtime is Node, but I thought that the minimal client was isomorphic, because it works fine inside `ayncData()`.
Also, I think that this used to work in previous versions of the module.

**Comment by danielroe** [comment]
@mornir If you want to use `createClient` in `nuxt.config`, you'll need to polyfill `node-fetch` (which is used by Nuxt for server-side fetch support within the app) - just follow [these instructions](https://github.com/node-fetch/node-fetch#loading-and-configuring-the-module) for patching your global fetch and let me know how things go 🙂

**Comment by mornir** [comment]
@danielroe Thanks for the quick reply! So I did it this way: https://github.com/mornir/movies-web/blob/dev/nuxt.config.js#L3

Now I no longer get the error `fetch is undefined`, but the results from `client.fetch` is now `undefined` (https://github.com/mornir/movies-web/blob/dev/nuxt.config.js#L72). Strange 🤔 Do you see anything wrong with my query?

**Comment by danielroe** [comment]
You'll need to set `dataset: 'production'`.

**Comment by mornir** [comment]
oh I see. thanks!

@danielroe What are your thoughts on this approach? Is it "smart" or would it better to use the `@sanity/client`? My goal with the minimal client is to shave off some kb on the bundle size (@sanity/client is huge!). Since `node-fetch` is very light and probably already included in the Nuxt framework, I think that this approach still makes sense, bundle-wise.

**Comment by danielroe** [comment]
@mornir Agreed - I think a very sensible approach. Using it in Nuxt config to generate routes shouldn't add to your bundle size but why add another dependency if you don't need to?
