### ISSUE TITLE
SanityMedia component

### ISSUE THREAD

**Issue by liqueflies** [nuxt-community/sanity-module#70]
### Is your feature request related to a problem? Please describe.
Hi! is there a possibility to add a  component also for Files? like the SanityImage component (https://github.com/nuxt-community/sanity-module/blob/main/src/components/sanity-image.ts)

### Describe the solution you'd like to see
I think that it will be the same component (without transformation parameters) because if I use the <SanityImage> slot the src in the scope is correct except for the basePath (https://github.com/nuxt-community/sanity-module/blob/main/src/components/sanity-image.ts#L6) that is `files` instead `images`

### Describe alternatives you've considered
Nothing

### Additional context
So maybe also for attachments or video you can do something like:

```
<SanityMedia>
  <template #default="{ src }">
     <a :href="src> Download </a>
  </template>
</SanityMedia>
```

**Comment by danielroe** [comment]
@liqueflies Good idea 👍

**Comment by liqueflies** [comment]
Hi @danielroe thanks for this!

I'm trying it out but SanityFile is not exported in the bundle.
If I check node_modules dist folder this is the situation:

![Screenshot 2021-04-23 at 14 21 26](https://user-images.githubusercontent.com/12168237/115874489-72760280-a444-11eb-92c1-ea75768f2ce9.png)

**Comment by liqueflies** [comment]
Like a charm ;)

Thank you so much <3
