### ISSUE TITLE
Add support for Nuxt Vite

### ISSUE THREAD

**Issue by egstad** [nuxt-community/sanity-module#71]
Not sure if this is the place to request this or not, but now that [@nuxt/vite](https://github.com/nuxt/vite) is a thing, it would be amazing to see this package add support! Please and thank you!

Currently the build crashes and emits this error:

```js
 ERROR  fetch is not defined                                                            22:26:58

  at Object.fetch (node_modules/@nuxtjs/sanity/dist/index.js:47:12)
  at Object.fetch (server.js:2057:24)
  at asyncData (server.js:3349:27)
  at promisify (server.js:574:15)
  at server.js:2510:23
  at Array.map (<anonymous>)
  at server (server.js:2507:51)
```

**Comment by danielroe** [comment]
@egstad Have you tried following nuxt/vite's suggested workaround?
```js
vite: {
    optimizeDeps: {
      exclude: ['@nuxtjs/sanity']
    }
  }
```

**Comment by egstad** [comment]
@danielroe sure did! same error unfortunately.

**Comment by danielroe** [comment]
@egstad Any chance of a reproduction then?

**Comment by philefstat** [comment]
@egstad did you find a solution to this?
